import { Catalog } from '@/types/product';

const PUBLIC_PRODUCTS = '/products';

export const MOCK_CATALOG: Catalog = {
  sellers: [
    {
      id: 'sell-celso',
      name: 'Celso Farm',
      farmName: 'Celso Farm',
      location: 'La Trinidad, Benguet',
      region: 'Cordillera Administrative Region (CAR)',
      province: 'Benguet',
      rating: 4.8,
      ratingCount: 214,
      verified: true,
      distanceKm: 251,
      deliveryFeePeso: 49,
    },
    {
      id: 'sell-verde',
      name: 'Verde Collective',
      farmName: 'Verde Collective',
      location: 'Silang, Cavite',
      region: 'Region IV-A (CALABARZON)',
      province: 'Cavite',
      rating: 4.6,
      ratingCount: 132,
      verified: true,
      distanceKm: 88,
      deliveryFeePeso: 39,
    },
    {
      id: 'sell-malabanan',
      name: 'Malabanan Farm',
      farmName: 'Malabanan Farm',
      location: 'Lipa, Batangas',
      region: 'Region IV-A (CALABARZON)',
      province: 'Batangas',
      rating: 4.4,
      ratingCount: 64,
      verified: true,
      distanceKm: 96,
      deliveryFeePeso: 45,
    },
    {
      id: 'sell-san-jose',
      name: 'San Jose Cooperative',
      farmName: 'San Jose Cooperative',
      location: 'Cabanatuan, Nueva Ecija',
      region: 'Region III (Central Luzon)',
      province: 'Nueva Ecija',
      rating: 4.5,
      ratingCount: 301,
      verified: true,
      distanceKm: 142,
      deliveryFeePeso: 59,
    },
    {
      id: 'sell-isla',
      name: 'Isla Orchards',
      farmName: 'Isla Orchards',
      location: 'Jordan, Guimaras',
      region: 'Region VI (Western Visayas)',
      province: 'Guimaras',
      rating: 4.7,
      ratingCount: 186,
      verified: true,
      distanceKm: 560,
      deliveryFeePeso: 89,
    },
    {
      id: 'sell-kitanglad',
      name: 'Kitanglad Ridge Farms',
      farmName: 'Kitanglad Ridge Farms',
      location: 'Malaybalay, Bukidnon',
      region: 'Region X (Northern Mindanao)',
      province: 'Bukidnon',
      rating: 4.9,
      ratingCount: 97,
      verified: true,
      distanceKm: 921,
      deliveryFeePeso: 119,
    },
  ],
  products: [
    {
      id: 'prod-1',
      sellerId: 'sell-celso',
      name: 'Highland Strawberries',
      category: 'fruits',
      price: 140,
      unit: 'kg',
      imageUrl: `${PUBLIC_PRODUCTS}/fruits.svg`,
      stockQty: 120,
      harvestDate: '2026-09-18',
      origin: 'La Trinidad, Benguet',
      storageTips: 'Keep refrigerated below 12°C. Best enjoyed within 2–3 days of delivery.',
      description:
        'Sweet, firm highland strawberries picked at first light. Grown in cool-climate seedbeds with natural compost, no growth boosters.',
      rating: 4.8,
      ratingCount: 214,
      tags: ['sweet', 'daily harvest'],
    },
    {
      id: 'prod-7',
      sellerId: 'sell-celso',
      name: 'Baguio Broccoli Crowns',
      category: 'vegetables',
      price: 120,
      unit: 'kg',
      imageUrl: `${PUBLIC_PRODUCTS}/vegetables.svg`,
      stockQty: 60,
      harvestDate: '2026-09-17',
      origin: 'La Trinidad, Benguet',
      storageTips: 'Chill and keep in a loosely closed bag. Blanch before freezing for longer storage.',
      description:
        'Dense, tight crowns harvested cold. A reliable highland crop favored for its crisp florets and clean flavor.',
      rating: 4.6,
      ratingCount: 98,
      tags: ['chilled harvest'],
    },
    {
      id: 'prod-8',
      sellerId: 'sell-celso',
      name: 'Carrot Crunch (Baguio)',
      category: 'vegetables',
      price: 90,
      unit: 'kg',
      imageUrl: `${PUBLIC_PRODUCTS}/vegetables.svg`,
      stockQty: 200,
      harvestDate: '2026-09-16',
      origin: 'La Trinidad, Benguet',
      storageTips: 'Store unwashed in the fridge, away from direct moisture. Trimming the tops keeps them crisp longer.',
      description:
        'Sweet, tender carrots from the Cordillera highlands. Ideal for juicing, stews, and fresh kilawin.',
      rating: 4.5,
      ratingCount: 121,
      tags: ['crisp', 'nutrition'],
    },
    {
      id: 'prod-3',
      sellerId: 'sell-verde',
      name: 'Hydroponic Romaine',
      category: 'vegetables',
      price: 75,
      unit: 'kg',
      imageUrl: `${PUBLIC_PRODUCTS}/vegetables.svg`,
      stockQty: 75,
      harvestDate: '2026-09-19',
      origin: 'Silang, Cavite',
      storageTips: 'Wrap in a damp paper towel inside the fridge. Best used within 4 days.',
      description:
        'Soil-free grown romaine with clean, crunchy leaves. Consistent quality through the year.',
      rating: 4.6,
      ratingCount: 132,
      tags: ['hydroponic', 'daily harvest'],
    },
    {
      id: 'prod-9',
      sellerId: 'sell-verde',
      name: 'Sweet Basil Bunches',
      category: 'vegetables',
      price: 45,
      unit: 'bunch',
      imageUrl: `${PUBLIC_PRODUCTS}/vegetables.svg`,
      stockQty: 90,
      harvestDate: '2026-09-19',
      origin: 'Silang, Cavite',
      storageTips: 'Stand stems in a glass of water and keep at room temperature, away from direct sun.',
      description:
        'Fragrant basil bunches trimmed fresh each morning. Aromatic lift for sauces, salads, and ginataan.',
      rating: 4.4,
      ratingCount: 41,
      tags: ['herbs', 'aromatic'],
    },
    {
      id: 'prod-6',
      sellerId: 'sell-malabanan',
      name: 'Native Sweet Papaya',
      category: 'fruits',
      price: 45,
      unit: 'kg',
      imageUrl: `${PUBLIC_PRODUCTS}/fruits.svg`,
      stockQty: 90,
      harvestDate: '2026-09-18',
      origin: 'Lipa, Batangas',
      storageTips: 'Ripen at room temperature, then chill. Pairs well for breakfast bowls and atsara.',
      description:
        'Naturally sweet papaya from Batangas orchards. A staple for fruit plates and traditional recipes.',
      rating: 4.4,
      ratingCount: 64,
      tags: ['sweet', 'tropical'],
    },
    {
      id: 'prod-4',
      sellerId: 'sell-san-jose',
      name: 'Dinorado White Rice',
      category: 'grains',
      price: 48,
      unit: 'kg',
      imageUrl: `${PUBLIC_PRODUCTS}/grains.svg`,
      stockQty: 1000,
      harvestDate: '2026-09-10',
      origin: 'Cabanatuan, Nueva Ecija',
      storageTips: 'Keep sealed in a cool, dry pantry. Milled weekly for freshness.',
      description:
        'Hand-pounded Dinorado from the Central Luzon rice bowl. Fluffy grains with a gentle, aromatic finish.',
      rating: 4.5,
      ratingCount: 301,
      tags: ['new harvest', 'household'],
    },
    {
      id: 'prod-5',
      sellerId: 'sell-kitanglad',
      name: 'Highland Arabica Coffee',
      category: 'grains',
      price: 380,
      unit: 'kg',
      imageUrl: `${PUBLIC_PRODUCTS}/grains.svg`,
      stockQty: 48,
      harvestDate: '2026-09-05',
      origin: 'Malaybalay, Bukidnon',
      storageTips: 'Store whole beans in an airtight jar away from heat and light. Grind only what you brew.',
      description:
        'Shade-grown Arabica from the Kitanglad mountain range. Chocolatey body with citrus notes, roasted to order.',
      rating: 4.9,
      ratingCount: 97,
      tags: ['specialty', 'shade-grown'],
    },
    {
      id: 'prod-2',
      sellerId: 'sell-isla',
      name: 'Carabao Mangoes',
      category: 'fruits',
      price: 110,
      unit: 'kg',
      imageUrl: `${PUBLIC_PRODUCTS}/fruits.svg`,
      stockQty: 85,
      harvestDate: '2026-09-15',
      origin: 'Jordan, Guimaras',
      storageTips: 'Ripen at room temperature until fragrant. Refrigerate after fully ripe for up to 4 days.',
      description:
        'Guimaras carabao mangoes — sweet, fiber-light, and world-renowned. Picked at the right stage and packed for transit.',
      rating: 4.7,
      ratingCount: 186,
      tags: ['premium', 'sweet'],
    },
  ],
  reviews: [
    {
      id: 'rev-1',
      productId: 'prod-1',
      author: 'Liza M.',
      rating: 5,
      comment: 'Sweet and fresh, exactly what we look for. Arrived the same day.',
      date: '2026-09-12',
    },
    {
      id: 'rev-2',
      productId: 'prod-1',
      author: 'Ramon D.',
      rating: 4,
      comment: 'Very good quality. Slightly pricier than the wet market but the freshness is consistent.',
      date: '2026-09-08',
    },
    {
      id: 'rev-3',
      productId: 'prod-2',
      author: 'Grace T.',
      rating: 5,
      comment: 'My kids eat these straight out of the box. Reordering weekly!',
      date: '2026-09-05',
    },
    {
      id: 'rev-4',
      productId: 'prod-5',
      author: 'Paolo S.',
      rating: 5,
      comment: 'The coffee is incredible — smooth and aromatic. Will buy again.',
      date: '2026-08-28',
    },
    {
      id: 'rev-5',
      productId: 'prod-3',
      author: 'Ann V.',
      rating: 4,
      comment: 'Crisp and clean. Good for meal prep.',
      date: '2026-08-20',
    },
    {
      id: 'rev-6',
      productId: 'prod-7',
      author: 'Nikki R.',
      rating: 5,
      comment: 'Beautiful crowns, no soft spots. Stored great for the week.',
      date: '2026-09-10',
    },
    {
      id: 'rev-7',
      productId: 'prod-4',
      author: 'Jomar B.',
      rating: 5,
      comment: 'Fluffy rice, aromatic. New harvest difference is real.',
      date: '2026-09-02',
    },
  ],
};